-- =====================================================
-- DATABASE MIGRATION - v5.0
-- Feature: Enable Cascading Delete for Categories
-- Description: Allows deleting categories. All products in that category will be deleted too.
--              Consequently, transaction details for those products will also be deleted.
-- =====================================================

USE db_kasir;

-- 1. Drop existing foreign key on produk table
-- (We use a dynamic approach in PHP, but for SQL file we assume standard or 'fk_produk_kategori' if named, 
--  however since we don't know the exact name generated by previous CREATE statements if they were anonymous,
--  users might need to check 'SHOW CREATE TABLE produk')

-- EXAMPLE (Adjust 'produk_ibfk_1' to your actual constraint name):
-- ALTER TABLE produk DROP FOREIGN KEY produk_ibfk_1;

-- 2. Drop the new constraint if it already exists (to avoid Error 121 Duplicate Key)
-- We wrap this in a way that helps manual execution. If this fails (because it doesn't exist), just continue.
-- For phpMyAdmin, you might need to ignore the error or run the DROP separately.
ALTER TABLE produk DROP FOREIGN KEY fk_produk_kategori;

-- 3. Add new foreign key with ID Kategori CASCADE
ALTER TABLE produk 
ADD CONSTRAINT fk_produk_kategori 
FOREIGN KEY (id_kategori) REFERENCES kategori(id_kategori) 
ON DELETE CASCADE;

SELECT 'Migration v5.0 (Cascading Category Delete) applied successfully!' as status;
